#!/usr/bin/env python3
"""
Build standalone per-platform exports.

Per PORTABILITY.md: "Generate compiled exports under `exports/<platform>/`
when useful. Compiled files are build artifacts, not sources of truth."

For each of the 15 skills and each of the 6 platforms, this writes one
self-contained file: the canonical `SKILL.md` followed by that platform's
`adapters/<platform>.md`, with a header stating this is a generated build
artifact and naming its source. Nothing here changes methodology, outputs,
quality gates or stop conditions -- it only concatenates what already
exists, exactly as PORTABILITY.md's adapter contract requires.

Run from repo root:
    python3 scripts/build_exports.py
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SKILLS_DIR = ROOT / "skills"
EXPORTS_DIR = ROOT / "exports"

PLATFORMS = ["generic", "chatgpt", "codex", "claude", "gemini", "cursor"]


def build():
    skill_dirs = sorted(p for p in SKILLS_DIR.iterdir() if p.is_dir())
    written = []

    for platform in PLATFORMS:
        out_dir = EXPORTS_DIR / platform
        out_dir.mkdir(parents=True, exist_ok=True)

        for sd in skill_dirs:
            skill_id = sd.name.split("-", 1)[1]
            skill_md = (sd / "SKILL.md").read_text()
            adapter_path = sd / "adapters" / f"{platform}.md"
            adapter_md = adapter_path.read_text()

            header = (
                f"<!--\n"
                f"  BUILD ARTIFACT -- do not edit directly.\n"
                f"  Generated by scripts/build_exports.py from:\n"
                f"    skills/{sd.name}/SKILL.md\n"
                f"    skills/{sd.name}/adapters/{platform}.md\n"
                f"  The canonical source is SKILL.md; the adapter below is a\n"
                f"  thin wrapper over it per PORTABILITY.md and\n"
                f"  shared/adapters/README.md -- it may not change purpose,\n"
                f"  procedure, outputs, quality gates or stop conditions.\n"
                f"  To change behavior, edit the source files and re-run\n"
                f"  scripts/build_exports.py.\n"
                f"-->\n\n"
            )

            content = header + skill_md.rstrip() + "\n\n---\n\n" + adapter_md.rstrip() + "\n"

            out_file = out_dir / f"{skill_id}.md"
            out_file.write_text(content)
            written.append(out_file)

    return written


def main():
    written = build()
    print(f"Wrote {len(written)} export files under {EXPORTS_DIR.relative_to(ROOT)}/ "
          f"({len(PLATFORMS)} platforms x {len(written) // len(PLATFORMS)} skills).")


if __name__ == "__main__":
    main()
